name: mentearn
description: A new Flutter project created for Google solution challenge


publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"


dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  firebase_core: ^1.12.0
  firebase_auth: ^3.3.7
  google_sign_in: ^5.2.1
  cloud_firestore: ^3.1.0
  firebase_storage: ^10.2.7
  image_picker: ^0.8.4+9
  file_picker: ^4.0.3
  path: ^1.8.0
  intl: ^0.17.0
  googleapis: ^7.0.0
  googleapis_auth: ^1.3.0
  url_launcher: ^6.0.17
  liquid_progress_indicator: ^0.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0


flutter:

  uses-material-design: true

  assets:
  - images/

  fonts:
  - family: Poppins
    fonts:
    - asset: fonts/Poppins-Bold.ttf
    - asset: fonts/Poppins-Regular.ttf
